#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# WeatheringMediatedErosion documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../python'))
sys.path.insert(0, os.path.abspath('../python/wme'))



# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# extensions = ['sphinx.ext.autodoc','sphinx.ext.githubpages','sphinx.ext.intersphinx',
#               'sphinx.ext.todo','sphinx.ext.napoleon','sphinx.ext.imgmath']
extensions = ['sphinx.ext.githubpages','sphinx.ext.intersphinx',
              'sphinx.ext.todo','sphinx.ext.napoleon',  #'sphinx.ext.imgmath'
              'sphinx.ext.mathjax' ]

mathjax_config = {
    'extensions': ['tex2jax.js'],
    'jax': ['input/TeX', 'output/HTML-CSS'],
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_parsers = {
   '.md': 'recommonmark.parser.CommonMarkParser',
}
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Weathering Mediated Erosion'
copyright = '2018, CPS'
author = 'CPS'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ''
# The full version, including alpha/beta/rc tags.
release = ''

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'
# html_theme = 'sphinxdoc'
# html_theme = 'haiku'
# html_theme = 'classic'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
# html_theme_options = {
#     "rightsidebar": "true"
# }
html_theme_options = {
#     'logo' : '../_images/icon1.png',
    'logo' : '../_images/wme_icon.png',
    'logo_name' : 'true',
    'description' : 'Weathering-driven weakening and coeval erosion of rock',
    'description_font_style' : 'italic',
    'show_related' : 'true',
    'code_font_size' : '0.7em',
    'page_width': '950px',
    'sidebar_width': '195px',
    'sidebar_text': 'blah'
#     'page_width': '1050px'
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static','_build/html/_static']


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     '**': [
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#     ]
# }


html_sidebars = {
    '**': [
        'about.html',
        'searchbox.html',
        'localtoc.html',
#         'globaltoc.html',
        'relations.html',
#         'sourcelink.html',
    ]
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'wmedoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'WeatheringMediatedErosion.tex', 
     'WeatheringMediatedErosion Documentation',
     'CPS', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'wme', 'WeatheringMediatedErosion Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'WeatheringMediatedErosion', 'WeatheringMediatedErosion Documentation',
     author, 'WeatheringMediatedErosion',
      'Weathering-driven weakening and coeval rock erosion.',
     'Miscellaneous'),
]


# Source inventories are named 'objects.inv' and can be wgetted
intersphinx_mapping = {
   'sphinx': ('http://www.sphinx-doc.org/en/master', None),
   
   'python': ('https://docs.python.org/3', None),
   
   'matplotlib': ('https://matplotlib.org',
                   (None,'./_intersphinx/matplotlib-objects.inv')),
#    'mpl_toolkits': ('https://matplotlib.org', (None,'matplotlib-objects.inv')),
    'mpl_toolkits': ('https://matplotlib.org', 
                     (None,'./_intersphinx/mpl_toolkits-objects.inv')),
   
   'np': ('https://docs.scipy.org/doc/numpy',
             (None, './_intersphinx/numpy-objects.inv')),
   'numpy': ('https://docs.scipy.org/doc/numpy',
             (None, './_intersphinx/numpy-objects.inv')),
               
   'skfmm': ('https://pythonhosted.org/scikit-fmm', None),
   
   'pandas': ('http://pandas.pydata.org/pandas-docs/stable', 
             (None, './_intersphinx/pandas-objects.inv')),
   
   'scipy': ('https://docs.scipy.org/doc/scipy/reference',
             (None, './_intersphinx/scipy-objects.inv'))
   }

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

